name: Build Mac app

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Get project files
        uses: actions/checkout@v4
      - name: Install Tkinter for Python
        run: brew install python-tk@3.14
      - name: Run Mac build script
        run: |
          chmod +x build_onefile_mac.command
          chmod +x setup_dev_mac.command
          ./build_onefile_mac.command

      - name: Make build available to download
        uses: actions/upload-artifact@v4
        with:
          name: DescargoMedicacionHOD1108-mac
          path: dist/
          if-no-files-found: error
